{
 "title": "Основная информация",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Запросы категорий",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_users", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "Заказы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "orders" }
   ]
  },
  {
   "title": "Уведомления",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "notifications", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Запросы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "requests{error!=\"error\"}",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  {
   "title": "Заказы по категориям",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Categories\".name as __name__,\n  COUNT(\"OrderItems\".uuid) as value\nFROM\n  \"OrderItems\"\nJOIN \"Products\" ON \"OrderItems\".\"productUUID\" = \"Products\".uuid\nJOIN \"Categories\" ON \"Products\".\"categoryUUID\" = \"Categories\".uuid\nGROUP BY \"Categories\".uuid, \"Categories\".name\nORDER BY value DESC\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Заказов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM \"Orders\" WHERE \"deletedAt\" IS NULL LIMIT 50 "
    }
   ]
  },
  {
   "title": "Товаров",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM \"Products\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Заказов на сумму",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"Products\".price)\nFROM \"Products\"\nJOIN \"OrderItems\" ON \"Products\".uuid = \"OrderItems\".\"productUUID\"\nJOIN \"Orders\" ON \"Orders\".uuid = \"OrderItems\".\"orderUUID\"\nWHERE \"Orders\".\"deletedAt\" IS NULL"
    }
   ]
  },
  {
   "title": " Заказы товаров",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Products\".name as __name__,\n  COUNT(\"OrderItems\".uuid) as value\nFROM\n  \"OrderItems\"\nJOIN \"Products\" ON \"OrderItems\".\"productUUID\" = \"Products\".uuid\nGROUP BY\n  \"productUUID\",\n  \"Products\".name\nORDER BY value DESC\nLIMIT\n  50"
    }
   ]
  }
 ]
}